<?xml version="1.0" ?>
<!DOCTYPE app_usuario [
  <!ELEMENT app_usuario (DATA_RECORD*)>
  <!ELEMENT DATA_RECORD (id?,nome?,data_nascimento?,login?,senha?)+>
  <!ELEMENT id (#PCDATA)>
  <!ELEMENT nome (#PCDATA)>
  <!ELEMENT data_nascimento (#PCDATA)>
  <!ELEMENT login (#PCDATA)>
  <!ELEMENT senha (#PCDATA)>
]>
<app_usuario>
  <DATA_RECORD>
    <id>1</id>
    <nome>Pricila Monteiro</nome>
    <data_nascimento>1997-09-02</data_nascimento>
    <login>pricila_monteiro</login>
    <senha>iiee32</senha>
  </DATA_RECORD>
  <DATA_RECORD>
    <id>2</id>
    <nome>marilia_andrade</nome>
    <data_nascimento>0977-08-05</data_nascimento>
    <login>marilia_andrade</login>
    <senha>123456</senha>
  </DATA_RECORD>
  <DATA_RECORD>
    <id>3</id>
    <nome>Kessiane Lima</nome>
    <data_nascimento>2001-09-02</data_nascimento>
    <login>ke_lima</login>
    <senha>trte42</senha>
  </DATA_RECORD>
  <DATA_RECORD>
    <id>4</id>
    <nome>Virginia dos Santos Silva</nome>
    <data_nascimento>1978-08-02</data_nascimento>
    <login>virginia1245</login>
    <senha>123456789</senha>
  </DATA_RECORD>
  <DATA_RECORD>
    <id>5</id>
    <nome>Joana Guaraldo</nome>
    <data_nascimento>2004-11-02</data_nascimento>
    <login>02_joana</login>
    <senha>05091874</senha>
  </DATA_RECORD>
  <DATA_RECORD>
    <id>6</id>
    <nome>Ricardo Felix</nome>
    <data_nascimento>1987-06-05</data_nascimento>
    <login>ricardo_felix</login>
    <senha>02ricado</senha>
  </DATA_RECORD>
  <DATA_RECORD>
    <id>7</id>
    <nome>Eliane Cardoso</nome>
    <data_nascimento>1975-06-05</data_nascimento>
    <login>eliane0102</login>
    <senha>eliane456789</senha>
  </DATA_RECORD>
  <DATA_RECORD>
    <id>8</id>
    <nome>Rafael Baltazar</nome>
    <data_nascimento>1985-06-05</data_nascimento>
    <login>rafael_balt</login>
    <senha>1234789rafael</senha>
  </DATA_RECORD>
</app_usuario>
